export const CONFIG = {
  world: {
    size: 240,
    segments: 160,
    maxHeight: 9,
    fogColor: 0x7c8b93,
    fogDensity: 0.019,
    boundaryRadius: 105,
  },
  path: {
    // control points of the pilgrim road (x, z), from shrine to boss arena
    points: [
      [0, 78], [6, 58], [-8, 36], [-4, 14], [8, -6], [2, -28], [0, -52],
    ],
    width: 5.2,
  },
  arena: { x: 0, z: -66, radius: 21 },
  shrine: { x: 0, z: 84 },

  player: {
    hp: 130,
    stamina: 100,
    staminaRegen: 34,
    rollCost: 22,
    sprintCost: 11,
    walkSpeed: 3.1,
    runSpeed: 5.6,
    sprintSpeed: 7.6,
    rollSpeed: 8.6,
    rollDuration: 0.52,
    rollIFrameStart: 0.04,
    rollIFrameEnd: 0.4,
    gourdCharges: 4,
    gourdHeal: 62,
    gourdTime: 1.35,
    focusMax: 3,
    focusPerHit: 0.36,
    hurtIFrames: 0.7,
    combo: [
      { anim: '2H_Melee_Attack_Slice', dmg: 15, speed: 1.35, lunge: 2.0, hitAt: 0.42, range: 2.9, arc: 1.7 },
      { anim: '2H_Melee_Attack_Chop', dmg: 17, speed: 1.35, lunge: 2.2, hitAt: 0.45, range: 2.9, arc: 1.6 },
      { anim: '2H_Melee_Attack_Stab', dmg: 19, speed: 1.3, lunge: 2.8, hitAt: 0.44, range: 3.3, arc: 1.0 },
      { anim: '2H_Melee_Attack_Spin', dmg: 30, speed: 1.22, lunge: 2.4, hitAt: 0.5, range: 3.1, arc: 3.4 },
    ],
    heavy: {
      anim: '2H_Melee_Attack_Spinning',
      baseDmg: 34,
      focusDmg: 26,
      speed: 1.15,
      lunge: 3.4,
      hitAt: 0.42,
      range: 3.4,
      arc: 3.6,
      minCharge: 0.35,
      maxCharge: 1.15,
    },
    stun: { cooldown: 16, duration: 3.6, range: 11 },
    clone: { cooldown: 30, duration: 13, count: 2, hp: 70, dmg: 10, attackRange: 2.7, speed: 5.2 },
    guard: { cooldown: 20, duration: 5, reduction: 0.75 },
    ult: { cooldown: 45, radius: 18 },
    quake: {
      cooldown: 35, radius: 14, height: 21, shellRadius: 3.1,
      tickDmg: 8, blastDmg: 220, castRange: 7,
      riseTime: 0.9, gatherTime: 1.8, holdTime: 0.5, fallTime: 0.38,
    },
    hole: {
      cooldown: 40, radius: 20, duration: 4.2, height: 5.6,
      pullSpeed: 8, swallowRadius: 2.7, bossSwallowRadius: 3.8,
      bossPullMul: 0.55, castRange: 9, formTime: 0.7, collapseTime: 0.7,
      debrisCount: 16, liftDistance: 7.5,
    },
  },

  enemies: {
    minion: {
      name: '骷髅小妖', model: 'skeletonMinion', hp: 46, dmg: 13, speed: 3.4,
      attackRange: 1.9, aggroRange: 13, attackCooldown: [1.1, 2.0], scale: 1.0,
      anims: ['Unarmed_Melee_Attack_Punch_A', 'Unarmed_Melee_Attack_Punch_B', 'Unarmed_Melee_Attack_Kick'],
      soul: 12,
    },
    rogue: {
      name: '骷髅刀客', model: 'skeletonRogue', hp: 62, dmg: 16, speed: 4.3,
      attackRange: 2.1, aggroRange: 15, attackCooldown: [0.9, 1.7], scale: 1.0,
      weapon: 'skeletonBlade', anims: ['1H_Melee_Attack_Slice_Diagonal', '1H_Melee_Attack_Slice_Horizontal', '1H_Melee_Attack_Stab'],
      soul: 20,
    },
    warrior: {
      name: '骷髅力士', model: 'skeletonWarrior', hp: 120, dmg: 24, speed: 2.7,
      attackRange: 2.4, aggroRange: 14, attackCooldown: [1.6, 2.6], scale: 1.12,
      weapon: 'skeletonAxe', anims: ['2H_Melee_Attack_Chop', '2H_Melee_Attack_Slice', '1H_Melee_Attack_Chop'],
      soul: 34,
    },
    mage: {
      name: '骷髅方士', model: 'skeletonMage', hp: 58, dmg: 15, speed: 2.9,
      attackRange: 12, keepDistance: 8, aggroRange: 17, attackCooldown: [2.2, 3.4], scale: 1.0,
      weapon: 'skeletonStaff', anims: ['Spellcast_Shoot'], ranged: true, projectileSpeed: 10,
      soul: 28,
    },
  },

  boss: {
    name: '白骨夫人',
    model: 'skeletonMage',
    weapon: 'skeletonStaff',
    hp: 980,
    scale: 1.85,
    speed: 3.6,
    phase2At: 0.5,
    soul: 500,
    attacks: {
      combo: { dmg: 26, range: 3.6, arc: 2.0 },
      slam: { dmg: 38, radius: 5.6, windup: 1.05 },
      volley: { dmg: 15, count: 3, speed: 12 },
      volley2: { dmg: 15, count: 5, speed: 13 },
      summonMax: 2,
    },
  },

  camera: {
    distance: 5.0,
    height: 1.7,
    fov: 55,
    sensitivity: 0.0023,
    minPitch: -0.9,
    maxPitch: 1.15,
  },

  audio: { musicVolume: 0.32, sfxVolume: 0.8 },
};
