/**
 * img-queries.mjs — 112 型装备的图片检索词表（人工校订，提高命中准确率）
 * 每项: [主查询(中文), 备用查询(英文/别名)]
 */
export const QUERIES = {
  /* ===== 解放军 空中 ===== */
  'J-20A': ['歼-20隐身战斗机 实机', 'J-20 Chengdu stealth fighter'],
  'J-16': ['歼-16战斗机 实机', 'Shenyang J-16 fighter'],
  'J-16D': ['歼-16D电子战飞机', 'J-16D electronic warfare aircraft'],
  'J-10C': ['歼-10C战斗机 实机', 'Chengdu J-10C fighter'],
  'J-11B': ['歼-11B战斗机', 'Shenyang J-11B fighter'],
  'Su-35S': ['苏-35战斗机 中国空军', 'Su-35S flanker E PLAAF'],
  'Su-30MKK': ['苏-30MKK战斗机', 'Su-30MKK China'],
  'JH-7A': ['歼轰-7A飞豹', 'JH-7A Flying Leopard'],
  'J-15': ['歼-15舰载机 辽宁舰', 'J-15 carrier fighter'],
  'J-35': ['歼-35舰载隐身战斗机', 'J-35 carrier stealth fighter'],
  'H-6K': ['轰-6K轰炸机', 'H-6K bomber'],
  'H-6J': ['轰-6J海军轰炸机', 'H-6J naval bomber'],
  'KJ-500A': ['空警-500预警机', 'KJ-500 AEW aircraft'],
  'KJ-2000': ['空警-2000预警机', 'KJ-2000 AWACS'],
  'Y-8Q': ['运-8反潜巡逻机 高新6号', 'Y-8Q anti-submarine aircraft'],
  'Y-9JB': ['运-9电子侦察机 高新8号', 'Y-9JB ELINT aircraft'],
  'WZ-7': ['无侦-7翔龙无人机', 'WZ-7 Soaring Dragon UAV'],
  'GJ-2': ['攻击-2无人机 翼龙2', 'Wing Loong II UAV'],
  'GJ-11': ['攻击-11隐身无人机 利剑', 'GJ-11 Sharp Sword UCAV'],
  'Y-20A': ['运-20运输机', 'Y-20 transport aircraft'],
  'Y-9': ['运-9运输机', 'Y-9 transport aircraft'],
  'Z-20': ['直-20直升机', 'Z-20 helicopter'],
  'Z-10ME': ['直-10武装直升机', 'Z-10 attack helicopter'],
  'Z-8L': ['直-8L运输直升机', 'Z-8L transport helicopter'],
  /* ===== 解放军 海上 ===== */
  'CV-Fujian': ['福建舰航空母舰', 'Fujian aircraft carrier Type 003'],
  'CV-Shandong': ['山东舰航空母舰', 'Shandong aircraft carrier'],
  'CV-Liaoning': ['辽宁舰航空母舰', 'Liaoning aircraft carrier'],
  'DDG-055': ['055型驱逐舰 南昌舰', 'Type 055 destroyer Renhai'],
  'DDG-052D': ['052D型驱逐舰', 'Type 052D destroyer'],
  'DDG-052C': ['052C型驱逐舰', 'Type 052C destroyer'],
  'DDG-051C': ['051C型驱逐舰', 'Type 051C destroyer'],
  'FFG-054A': ['054A型护卫舰', 'Type 054A frigate'],
  'FFG-054B': ['054B型护卫舰', 'Type 054B frigate'],
  'FFL-056A': ['056A型轻型护卫舰', 'Type 056A corvette'],
  'PGG-022': ['022型导弹艇', 'Type 022 Houbei missile boat'],
  'LHA-076': ['076型两栖攻击舰 四川舰', 'Type 076 Sichuan amphibious assault ship'],
  'LHD-075': ['075型两栖攻击舰 海南舰', 'Type 075 landing helicopter dock'],
  'LPD-071': ['071型综合登陆舰', 'Type 071 amphibious transport dock'],
  'LST-072A': ['072A型坦克登陆舰', 'Type 072A landing ship tank'],
  'LSM-073A': ['073A型登陆舰', 'Type 073A landing ship'],
  'Shuiqiao': ['解放军新型登陆驳船 栈桥', 'China landing barge Shuiqiao'],
  'RoRo-Civ': ['渤海翡珠 滚装船 军事运输', 'China roll-on roll-off ferry military'],
  'SS-039C': ['039C型潜艇 元级', 'Type 039C Yuan class submarine'],
  'SS-039B': ['039B型潜艇', 'Type 039B submarine'],
  'SS-Kilo': ['基洛级潜艇 中国海军', 'Kilo class submarine China'],
  'SSN-093B': ['093型核潜艇 商级', 'Type 093 Shang class SSN'],
  'CCG-Zhaotou': ['海警2901 万吨海警船', 'China Coast Guard 2901 cutter'],
  'Militia-Boat': ['海上民兵 渔船', 'China maritime militia fishing vessel'],
  /* ===== 解放军 陆上 ===== */
  'BDE-Amph': ['ZBD-05两栖步兵战车', 'ZBD-05 amphibious fighting vehicle'],
  'BDE-Marine': ['海军陆战队 05式两栖突击车', 'PLA marine ZTD-05'],
  'BDE-Airborne': ['空降兵 ZBD-03空降战车', 'ZBD-03 airborne fighting vehicle'],
  'BDE-Heavy': ['99A式主战坦克', 'ZTZ-99A main battle tank'],
  'BDE-SOF': ['解放军特种部队', 'PLA special forces'],
  'BDE-PHL16': ['PHL-191远程火箭炮 箱式', 'PHL-16 PCH-191 rocket launcher'],
  'BDE-PHL03': ['PHL-03远程火箭炮', 'PHL-03 300mm MLRS'],
  'BDE-SRBM': ['东风-15弹道导弹发射车', 'DF-15 ballistic missile TEL'],
  'BDE-SRBM16': ['东风-16弹道导弹', 'DF-16 ballistic missile'],
  'BDE-DF17': ['东风-17高超音速导弹', 'DF-17 hypersonic missile'],
  'BDE-LACM': ['长剑-10巡航导弹发射车', 'DF-10 CJ-10 cruise missile TEL'],
  'BDE-ASBM': ['东风-26弹道导弹', 'DF-26 ballistic missile launcher'],
  'SAM-HQ9B': ['红旗-9防空导弹', 'HQ-9 surface to air missile'],
  'SAM-S400': ['S-400防空导弹系统', 'S-400 SAM system'],
  'RADAR-PLA': ['大型相控阵预警雷达', 'large phased array radar'],
  'EW-Station': ['电子对抗 干扰车', 'electronic warfare jamming vehicle'],
  'BEACHHEAD': ['两栖登陆 滩头', 'amphibious landing beachhead'],
  /* ===== 台军 空中 ===== */
  'F-16V': ['F-16V战斗机 台湾空军', 'F-16V Viper Taiwan air force'],
  'F-16C70': ['F-16 Block 70战斗机', 'F-16 Block 70 Viper'],
  'Mirage-2000': ['幻象2000战斗机 台湾', 'Mirage 2000-5 Taiwan'],
  'IDF': ['IDF经国号战斗机', 'F-CK-1 Ching-kuo IDF fighter'],
  'E-2K': ['E-2K预警机 台湾', 'E-2K Hawkeye Taiwan'],
  'P-3C': ['P-3C反潜机 台湾', 'P-3C Orion Taiwan'],
  'AH-64E': ['AH-64E阿帕契直升机 台湾', 'AH-64E Apache Taiwan'],
  'AH-1W': ['AH-1W超级眼镜蛇 台湾', 'AH-1W SuperCobra Taiwan'],
  'UAV-Teng': ['腾云无人机 台湾', 'Teng Yun UAV Taiwan'],
  'UAV-Albat': ['锐鸢无人机 台湾', 'Albatross UAV Taiwan'],
  /* ===== 台军 海上 ===== */
  'DDG-KeeLung': ['基隆级驱逐舰', 'Kee Lung class destroyer Kidd'],
  'FFG-ChengKung': ['成功级巡防舰', 'Cheng Kung class frigate'],
  'FFG-KangDing': ['康定级巡防舰 拉法叶', 'Kang Ding class La Fayette frigate'],
  'PGG-TuoChiang': ['沱江级巡逻舰', 'Tuo Chiang class corvette'],
  'PGG-KuangHua6': ['光华六号飞弹快艇', 'Kuang Hua VI missile boat'],
  'PC-ChingChiang': ['锦江级巡逻舰', 'Ching Chiang class patrol ship'],
  'SS-HaiKun': ['海鲲号潜艇', 'Hai Kun submarine Taiwan'],
  'SS-HaiLung': ['海龙号潜艇 剑龙级', 'Hai Lung class submarine'],
  'MineLayer-Min': ['快速布雷艇 台湾海军', 'fast minelaying boat Taiwan navy'],
  'LPD-YuShan': ['玉山军舰 船坞运输舰', 'Yu Shan class LPD Taiwan'],
  /* ===== 台军 陆上 ===== */
  'BDE-ROC-Armor': ['M1A2T主战坦克 台湾', 'M1A2T Abrams Taiwan army'],
  'BDE-ROC-Mech': ['CM-34云豹装甲车', 'CM-34 Clouded Leopard IFV'],
  'BDE-ROC-Inf': ['国军步兵 红隼火箭弹', 'Taiwan army infantry Kestrel'],
  'BDE-ROC-Marine': ['台湾海军陆战队 AAV7', 'Taiwan marine corps AAV7'],
  'BDE-ROC-Reserve': ['台湾后备动员 教召', 'Taiwan reservist mobilization'],
  'BN-ROC-SOF': ['台湾陸軍航特部特戰', 'Taiwan special forces'],
  'BN-HIMARS': ['海马斯火箭炮 台湾', 'M142 HIMARS Taiwan'],
  'BN-Harpoon-CDS': ['岸置鱼叉飞弹 台湾', 'Harpoon coastal defense system Taiwan'],
  'BN-HF-Coastal': ['雄风三型飞弹 机动发射车', 'Hsiung Feng III missile launcher'],
  'BN-HF3ER': ['增程型雄风三型飞弹', 'Hsiung Feng III extended range'],
  'BN-HF2E': ['雄风二E巡航飞弹', 'Hsiung Feng IIE cruise missile'],
  'BN-YunFeng': ['云峰飞弹 中科院', 'Yun Feng missile Taiwan'],
  'BN-M109': ['M109A6自走炮', 'M109A6 Paladin howitzer'],
  'SAM-PAC3': ['爱国者三型飞弹 台湾', 'Patriot PAC-3 Taiwan'],
  'SAM-TK3': ['天弓三型飞弹', 'Tien Kung III missile'],
  'SAM-TK2': ['天弓二型飞弹', 'Tien Kung II missile'],
  'SAM-Land': ['陆剑二防空飞弹', 'Land Sword II SAM Taiwan'],
  'SAM-Skyguard': ['天兵防砲系统 35快砲', 'Skyguard 35mm air defense'],
  'RADAR-ROC': ['乐山雷达站 铺路爪', 'Leshan PAVE PAWS radar Taiwan'],
  'RADAR-ROC-Mobile': ['机动战管雷达 台湾', 'mobile air defense radar Taiwan'],
  /* ===== 美日 ===== */
  'F-35A': ['F-35A闪电II战斗机', 'F-35A Lightning II'],
  'F-22A': ['F-22猛禽战斗机', 'F-22 Raptor'],
  'B-1B': ['B-1B枪骑兵轰炸机', 'B-1B Lancer bomber'],
  'CVN-Nimitz': ['尼米兹级核动力航母', 'Nimitz class aircraft carrier'],
  'DDG-Burke': ['阿利伯克级驱逐舰', 'Arleigh Burke class destroyer'],
  'SSN-Virginia': ['弗吉尼亚级核潜艇', 'Virginia class submarine'],
  'JMSDF-DDG': ['摩耶级驱逐舰 海上自卫队', 'Maya class destroyer JMSDF']
};
